# AWS related variables - Modify region and instance type as per your requirement
variable "region" {
  description = "Newsletter automation ec2 instance deploy region"
  type        = string
  default     = "us-east-1"
}

variable "newsletter_ec2_inst_type" {
  description = "declaring ec2 instance type for newsletter for test"
  default     = "t3.small"
}

variable "key_name" {
  type        = string
  default     = "newsletter-key-pair"
  description = "Key-pair generated by Terraform"
  sensitive = true
}

# Modify default value as per your requirement
variable "profile" {
  default = "personal"
  type    = string

}
# path to temp key folder name
variable "temp_path" {
  type        = string
  description = "Path to the PEM private key file"
  default = "/tmp"
}
# folder name
variable "foldername" {
  type    = string
  default = "qxf2-lambdas"
}
# zip file name
variable "zipfilename" {
  type = string
  default = "lambda_code.zip"
}
# home directory
variable "homedir" {
  type = string
  default = "/home/ubuntu"  
}
# remote user-ubuntu
variable "remoteuser" {
  type = string
  description = "remote user name"
  default = "ubuntu"
}